[package]
name = "keyboard_layout_optimizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
rusqlite = "0.32.1"
rayon = "1.8"
fastrand = "2.3.0"
rand_distr = "0.4.3"
plotters = "0.3"
bitflags = "2.9.0"
